tasks:
  install:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  lint:
    image: node:carbon
    command:
      - yarn
    args:
      - lint
  test:
    image: node:carbon
    command:
      - yarn
    args:
      - test
  build:
    image: node:carbon
    command:
      - yarn
    args:
      - build

workflow:
  - install
  - sail:parallel:
    - lint
    - test
    - prettier
  - build
