name: Code Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check codebase (lint and typecheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Installation
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn run test

      - name: Type Check
        run: yarn run typecheck

      - name: Library Build
        run: yarn run build

      - name: Storybook Build
        run: yarn run storybook:build
