name: Code Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check codebase (lint and typecheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check Code ${{ matrix.node-version }}
        run: pnpm lint

      - name: Build ${{ matrix.node-version }}
        run: pnpm build
